import test from 'node:test'
import assert from 'node:assert/strict'
import { CHASSIS_KEYS, TRACK_KEYS } from '../shared/kart.js'
import { SIM_VERSION } from '../shared/constants.js'
import { PAR, PAR_SIM_VERSION } from '../shared/kart-par.js'

test('par covers every track and chassis', () => {
  for (const track of TRACK_KEYS) {
    for (const chassis of CHASSIS_KEYS) {
      const ms = PAR[track]?.[chassis]
      assert.equal(typeof ms, 'number', `${track}/${chassis} missing`)
      assert.ok(Number.isFinite(ms), `${track}/${chassis} is not finite`)
      // A three-lap race: nothing under half a minute, nothing over five.
      assert.ok(ms > 30_000 && ms < 300_000, `${track}/${chassis} implausible: ${ms}`)
    }
  }
})

// The pair that goes stale together: a tuning change means a new SIM_VERSION
// and a regenerated table, and this fails if only one of the two happened.
test('the committed par table was generated by this sim version', () => {
  assert.equal(PAR_SIM_VERSION, SIM_VERSION)
})
