// Generated by scripts/kart-par.mjs — do not edit by hand.
//
// Par is the AI's three-lap time in milliseconds, driven down the centreline in
// the named chassis. Beating the daily means beating the AI. Regenerate after
// any tuning change, in the same commit as the SIM_VERSION bump.
export const PAR_SIM_VERSION = 1

export const PAR = {
  circuit: { coupe: 175483, wedge: 163950, van: 179583, roadster: 172867, openwheel: 177333, bike: 163017 },
  bayside: { coupe: 109333, wedge: 100300, van: 113867, roadster: 112150, openwheel: 115267, bike: 102550 },
  grove: { coupe: 132917, wedge: 121917, van: 138433, roadster: 136367, openwheel: 140150, bike: 124667 },
  foundry: { coupe: 159200, wedge: 145983, van: 165817, roadster: 163367, openwheel: 167900, bike: 149333 },
  cliff: { coupe: 187950, wedge: 172300, van: 195700, roadster: 192867, openwheel: 198217, bike: 176283 },
  fracture: { coupe: 213750, wedge: 196017, van: 222617, roadster: 219317, openwheel: 225367, bike: 200517 },
}

export default PAR
