// Generated by scripts/kart-par.mjs — do not edit by hand.
//
// Par is the AI's three-lap time in milliseconds, driven down the centreline in
// the named chassis. Beating the daily means beating the AI. Regenerate after
// any tuning change, in the same commit as the SIM_VERSION bump.
export const PAR_SIM_VERSION = 1

export const PAR = {
  circuit: { coupe: 199183, wedge: 190233, van: 205433, roadster: 201517, openwheel: 202100, bike: 190917 },
  bayside: { coupe: 122317, wedge: 116050, van: 127183, roadster: 126433, openwheel: 129550, bike: 117250 },
  grove: { coupe: 151567, wedge: 141700, van: 157567, roadster: 154317, openwheel: 159917, bike: 143117 },
  foundry: { coupe: 179367, wedge: 165433, van: 186483, roadster: 181083, openwheel: 185650, bike: 167500 },
  cliff: { coupe: 209817, wedge: 195500, van: 220133, roadster: 213950, openwheel: 219283, bike: 196167 },
  fracture: { coupe: 243933, wedge: 224483, van: 250067, roadster: 244717, openwheel: 250967, bike: 226767 },
}

export default PAR
