// Regenerates shared/kart-par.js — the AI's three-lap time for all 36
// track/chassis pairs, which is what the daily uses as par. Run it by hand
// after a tuning change and commit the result:
//
//   node scripts/kart-par.mjs
//
import { writeFileSync } from 'node:fs'
import { SIM_VERSION } from '../shared/constants.js'
import { CHASSIS_KEYS, TRACK_KEYS, addKart, begin, createRace, step } from '../shared/kart.js'

// Eight minutes of ticks. A three-lap par is nowhere near this; the ceiling is
// here so a track the AI cannot get round fails loudly instead of hanging.
const CEILING = 60 * 60 * 8

function parFor(track, chassis) {
  const state = createRace([], 1, track)
  // Seated as a person, then handed to the AI: addKart deals an AI its own
  // chassis and its own line offset, and par needs the named chassis on the
  // centreline so this regenerates identically every time.
  const kart = addKart(state, { id: 1, name: 'par', chassis })
  kart.ai = true
  begin(state)
  for (let i = 0; i < CEILING && kart.finished === null; i++) step(state, {})
  if (kart.finished === null) throw new Error(`${track}/${chassis}: the AI never finished`)
  return Math.round(kart.finished * 1000)
}

const table = {}
for (const track of TRACK_KEYS) {
  table[track] = {}
  for (const chassis of CHASSIS_KEYS) {
    table[track][chassis] = parFor(track, chassis)
    process.stdout.write(`${track}/${chassis} ${table[track][chassis]}ms\n`)
  }
}

const body = TRACK_KEYS.map(
  (t) => `  ${t}: { ${CHASSIS_KEYS.map((c) => `${c}: ${table[t][c]}`).join(', ')} },`
).join('\n')

writeFileSync(
  new URL('../shared/kart-par.js', import.meta.url),
  `// Generated by scripts/kart-par.mjs — do not edit by hand.
//
// Par is the AI's three-lap time in milliseconds, driven down the centreline in
// the named chassis. Beating the daily means beating the AI. Regenerate after
// any tuning change, in the same commit as the SIM_VERSION bump.
export const PAR_SIM_VERSION = ${SIM_VERSION}

export const PAR = {
${body}
}

export default PAR
`
)
